# Generated by Django 5.2.9 on 2026-02-04 06:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('eventos', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='evento',
            name='foto',
            field=models.FileField(default=1, upload_to='flayers'),
            preserve_default=False,
        ),
    ]
